# Generated by Django 5.1.1 on 2025-08-08 13:55

import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(default=subjects.models.generate_subject_id, max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
