# Generated by Django 5.1.1 on 2025-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2euDtcTkd94RX1PIDEYODsi8a3oxk9Pb', editable=False, max_length=32, unique=True),
        ),
    ]
