# Generated by Django 5.1.1 on 2025-08-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='z8kNcJ3WmM6iinH7s3OHuqvG7NKl1eFF', editable=False, max_length=32, unique=True),
        ),
    ]
