# Generated by Django 5.1.1 on 2025-08-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='QVSu54uxNcJ8MJoEEBTUR1XZ2sO9eGcZ', editable=False, max_length=32, unique=True),
        ),
    ]
