# Generated by Django 5.1.1 on 2025-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5qyHzHmavEO5YiKPYEcg1s1IzSSpHAm7', editable=False, max_length=32, unique=True),
        ),
    ]
