# Generated by Django 5.1.1 on 2025-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='R8MNkR4oL9sM9xvqvv07h5uKqpp4rgH3', editable=False, max_length=32, unique=True),
        ),
    ]
