# Generated by Django 5.1.1 on 2025-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tMoVjNz8aEIwIbfcAJ9i32i3KnO0vAxr', editable=False, max_length=32, unique=True),
        ),
    ]
