# Generated by Django 5.1.1 on 2025-08-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UbUAngTa8tM1WpgLt39frfstMaHSIgTt', editable=False, max_length=32, unique=True),
        ),
    ]
