# Generated by Django 5.1.1 on 2025-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='IFP65Z1jc5DuxMVKHJblGUyPABWieIRU', editable=False, max_length=32, unique=True),
        ),
    ]
