# Generated by Django 5.1.1 on 2025-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pffDmykEr2ISWSmqgsS0Td3JIrMa8rFJ', editable=False, max_length=32, unique=True),
        ),
    ]
