# Generated by Django 5.1.1 on 2025-08-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0024_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SnsszpbZRGKetyIct73RegU0wAsgDSmT', editable=False, max_length=32, unique=True),
        ),
    ]
