# Generated by Django 5.1.1 on 2025-08-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0025_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='TTQFRtDH1wDLpzvY6LKIPTUQIsF67qyu', editable=False, max_length=32, unique=True),
        ),
    ]
