# Generated by Django 5.1.1 on 2025-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0026_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SjuROsyzvfxxe9PPjrFmCTWlwwvjJiBW', editable=False, max_length=32, unique=True),
        ),
    ]
