# Generated by Django 5.1.1 on 2025-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0027_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='t5RgYFevwR04QyY7GGNlEm55PX87JcaM', editable=False, max_length=32, unique=True),
        ),
    ]
