# Generated by Django 5.1.1 on 2025-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0029_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='PgMvm43YiIkqYKfYJabMNm1FKZPV73H7', editable=False, max_length=32, unique=True),
        ),
    ]
