# Generated by Django 5.1.1 on 2025-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0030_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SwNk8tXNTetPt00nRmYukl8JV6Tc9v1K', editable=False, max_length=32, unique=True),
        ),
    ]
