# Generated by Django 5.1.1 on 2025-08-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0033_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='YSs6iGedM3VtnebAwFdPTIdZT4wP9IAS', editable=False, max_length=32, unique=True),
        ),
    ]
