# Generated by Django 5.1.1 on 2025-08-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0036_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xEwYndR93trxtRefo1IVfGpi2Ju5jdlE', editable=False, max_length=32, unique=True),
        ),
    ]
