# Generated by Django 5.1.1 on 2025-08-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0037_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yDgnRNaDF3mOf2Q6wxkIlbFgN9ZQ4bqy', editable=False, max_length=32, unique=True),
        ),
    ]
