# Generated by Django 5.1.1 on 2025-08-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0041_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NglS4Em6HYKcVlHXbXbpUb6gaRNCjlyk', editable=False, max_length=32, unique=True),
        ),
    ]
