# Generated by Django 5.1.1 on 2025-08-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0042_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='MfZHNQWZsbLFy4f8rhZbmR17SJtvCuuU', editable=False, max_length=32, unique=True),
        ),
    ]
