# Generated by Django 5.1.1 on 2025-08-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0044_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='X08FQMOdOt14D6cYMZfV8hzm8Akq3ZVG', editable=False, max_length=32, unique=True),
        ),
    ]
