# Generated by Django 5.1.1 on 2025-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0045_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='b5N7usmax8siYFNDmIc2Y8gKtfX4J61H', editable=False, max_length=32, unique=True),
        ),
    ]
