# Generated by Django 5.1.1 on 2025-08-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0046_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pPqr4LsBiOflL6eduzBvtksehOBE9ktl', editable=False, max_length=32, unique=True),
        ),
    ]
