# Generated by Django 5.1.1 on 2025-08-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0047_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1k5NXcqzZNQasC44gyqbUjxzFWtF6GP2', editable=False, max_length=32, unique=True),
        ),
    ]
