# Generated by Django 5.1.1 on 2025-08-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0049_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KcFk1OptJrgDfW6oXJFaAIeVTa1mfGtF', editable=False, max_length=32, unique=True),
        ),
    ]
