# Generated by Django 5.1.1 on 2025-08-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_subjectenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='students',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subjects',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='semesterenrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='semesters.batch'),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='max_students',
            field=models.PositiveIntegerField(default=0, help_text='0 means no limit'),
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='semester_enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='semesters.semesterenrollment'),
        ),
        migrations.AlterField(
            model_name='semesterenrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='semesters.semester'),
        ),
        migrations.AlterField(
            model_name='semestersubject',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_name', 'semester')},
        ),
    ]
