# Generated by Django 5.1.1 on 2025-08-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
