# Generated by Django 5.1.1 on 2025-08-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=255, unique=True),
        ),
    ]
