# Generated by Django 5.1.1 on 2025-08-08 12:33

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=teachers.models.generate_teacher_id, max_length=20, unique=True),
        ),
    ]
