# Generated by Django 5.1.1 on 2025-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='no_of_students',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
